# MSNA 2025 Project UIDs
asset_uids:
  - "aA92YScayJLNUjkxBVQWWE"  # AFG2305_MSNA_WoAA_2025 (678 submissions)
  - "aRkGzrupjCmsJFW4puMkXu"  # AFG2305_MSNA_WoAA_2025 (49258 submissions)
  - "aGmsSuuhy8oGjBCXgmF5Pp"  # REACH RCA MSNA 2025 - CAR
  - "avwAc2bcM8onaYY2Zn7LNS"  # REACH_DRC_MSNA_2025 - DRC
  - "ammGxyDoSNd8V2JEvVuUoS"  # MSNA_2025_KI - DRC
  - "atCg2LRjwtY4tcbSxqzpuG"  # Multi-Sectoral Needs Assessment (MSNA) 2025 - Ethiopia
  - "a4m6kLJYrr5E6kXNeRsdiP"  # HTI2502_REACH_MSNA - Haiti
  - "aSis5zgHnVZ8nNGWct6req"  # LBN MSNA 2025 (v2) - Lebanon
  - "arnMZpQ8FmHcWVZyhb67ns"  # MSNA 2025 - Mali
  - "aoM5d2pWGy3FwyT9ssm2L7"  # Multi-Sector Needs Assessment (MSNA) 2025 - Myanmar
  - "aenhZmqkmPGB6wsEw3aiiV"  # REACH SOM2503 MSNA 2025 HNRP - Somalia
  - "ak5iQFpNGQpXcgGRrpEKjN"  # REACH_KEN_2025_MSNA - Somalia
  - "aFUeVboh9TJtLAqDMwL8ov"  # REACH_SOM2503_MSNA_2025_IPC - Somalia
  - "aCdzAaiGS5hAyMukmda6FW"  # UKR2502_MSNA_2025 - Ukraine

